#!/bin/bash
NIFI_DIRNAME=${PARCEL_DIRNAME:-"<PARCEL-NAME>"}
export CDH_NIFI_HOME=$PARCELS_ROOT/$NIFI_DIRNAME

if [ -n "${HADOOP_CLASSPATH}" ]; then
  export HADOOP_CLASSPATH="${HADOOP_CLASSPATH}:$PARCELS_ROOT/$HADOOP_WASB_DIRNAME/lib/hadoop/lib/*"
else
  export HADOOP_CLASSPATH="$PARCELS_ROOT/$HADOOP_WASB_DIRNAME/lib/hadoop/lib/*"
fi
